name: quick_start_scripts
description: Quick start scripts for Stelliberty project
publish_to: 'none'

environment:
  sdk: '^3.9.2'

dependencies:
  args: ^2.6.0
  path: ^1.9.1
  yaml: ^3.1.2
  http: ^1.2.2
  archive: ^4.0.7

dev_dependencies:
  lints: ^6.0.0